version: '3.9'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: kanban
    volumes:
      - mongo_data:/data/db
    networks:
      - kanban-net

  n8n:
    image: n8nio/n8n:1.106.3
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=${N8N_MONGODB_URL:-mongodb://mongo:27017/n8n}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_HOST=${N8N_HOST:-0.0.0.0}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-change-me}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - kanban-net

networks:
  kanban-net:
    driver: bridge

volumes:
  mongo_data:
  n8n_data:
