export enum RealtimeEvents {
    BoardCreated = 'board.created',
    BoardUpdated = 'board.updated',
    BoardDeleted = 'board.deleted',
    TaskCreated = 'task.created',
    TaskUpdated = 'task.updated',
    TaskMoved = 'task.moved',
    TaskDeleted = 'task.deleted',
    ColumnCreated = 'column.created',
    ColumnUpdated = 'column.updated',
    ColumnDeleted = 'column.deleted',
    ExportRequested = 'export.requested',
    ExportCompleted = 'export.completed',
    ExportFailed = 'export.failed',
}